import sys
fout=open(sys.argv[2],'w')
with open(sys.argv[1],'r') as fin:
    for sentence in fin:
        sentence=sentence.replace(u"\ufeff", '')
        sentence=sentence.replace(u"\u200c", '')
        sentence=sentence.replace(u"\u200b", '')  
        sentence=sentence.replace(u"\u200d", '')    
        sentence=sentence.replace(u"\u2009", '')                                                            
        sentence=sentence.replace(u"\u201d", '')
        sentence=sentence.replace(u"\u00A0", '')
        sentence=sentence.replace(u"\x01", '')
        sentence=sentence.replace(u"\x03", '')
        sentence=sentence.replace(u"\x14", '')
        sentence=sentence.replace(u"\x16", '')                                                                           
        sentence=sentence.replace("’", '')
        sentence=sentence.replace("‘", '')
        sentence=sentence.replace("—", '') 
        sentence=sentence.replace("…", '') 
        sentence=sentence.replace("*", '')                                         
        sentence=sentence.replace("॥", '')                    
        sentence=sentence.replace("|", '')         
        sentence=sentence.replace("+", '')         
        sentence=sentence.replace("–", '')         
        sentence=sentence.replace('̃', '')         
        sentence=sentence.replace("~", '')   
        sentence=sentence.replace("/", '')  
        sentence=sentence.replace("ː", '')                                                     
        sentence=sentence.replace("-", '') 
        sentence=sentence.replace("“", '')                
        sentence=sentence.replace("̃", '')        
        fout.write(sentence)

fout.close()

